---
kind: pipeline
name: default

steps:
        - name: restore-cache
          image: drillster/drone-volume-cache
          settings:
                  restore: true
                  mount:
                          - /home/user/.sbt
                          - /home/user/.ivy2
                  volumes:
                          - name: cache
                            path: /cache

        - name: build
          image: tooom/docker-scala-node
          commands:
                  - . ~/.nvm/nvm.sh
                  - sbt clean stage

        - name: save-cache
          image: drillster/drone-volume-cache
          settings:
                  rebuild: true
                  mount:
                          - /home/user/.sbt
                          - /home/user/.ivy2
                  volumes:
                          - name: cache
                            path: /cache

volumes:
        - name: cache
          host:
                  path: /opt/drone/cache
