---
kind: pipeline
name: default

clone:
        disable: true

steps:

        - name: clone
          image: plugins/git:next

        - name: restore-cache
          image: drillster/drone-volume-cache
          settings:
                  restore: true
                  mount:
                          - .sbt
                          - .ivy2
          volumes:
                  - name: cache
                    path: /cache

        - name: build
          image: tooom/docker-scala-node
          commands:
                  - ls -al
                  - . ~/.nvm/nvm.sh
                  - sbt -Duser.home=$PWD clean stage

        - name: save-cache
          image: drillster/drone-volume-cache
          settings:
                  rebuild: true
                  mount:
                          - .sbt
                          - .ivy2
          volumes:
                  - name: cache
                    path: /cache

volumes:
        - name: cache
          host:
                  path: /opt/drone/cache
