---
kind: pipeline
name: default

clone:
        disable: true

steps:

        - name: clone
          image: plugins/git:next

        - name: restore-cache
          image: drillster/drone-volume-cache
          settings:
                  restore: true
                  mount:
                          - .sbt
                          - .ivy2
                          - ui/node_modules
                          - ui/bower_components
          volumes:
                  - name: cache
                    path: /cache

        - name: build
          image: tooom/docker-scala-node
          commands:
                  - . ~/.nvm/nvm.sh
                  - sbt -Duser.home=$PWD clean docker:stage

        - name: docker
          image: plugins/docker
          settings:
                  context: target/docker/stage
                  dockerfile: target/docker/stage/Dockerfile
                  repo: tooom
                  auto_tag: true
                  secrets: [ docker_username, docker_password ]

        - name: save-cache
          image: drillster/drone-volume-cache
          settings:
                  rebuild: true
                  mount:
                          - .sbt
                          - .ivy2
                          - ui/node_modules
                          - ui/bower_components
          volumes:
                  - name: cache
                    path: /cache

volumes:
        - name: cache
          host:
                  path: /opt/drone/cache
