---
kind: pipeline
name: default
workspace:
        base: /home/user
        path: /src


steps:
        - name: restore-cache
          image: drillster/drone-volume-cache
          settings:
                  restore: true
                  mount:
                          - .sbt
                          - .ivy2
                  volumes:
                          - name: cache
                            path: /cache

        - name: build
          image: tooom/docker-scala-node
          commands:
                  - id
                  - mkdir -p /home/user/.sbt/boot/
                  - find /home/user -exec ls -ald {} \;
                  - sbt clean stage

        - name: save-cache
          image: drillster/drone-volume-cache
          settings:
                  rebuild: true
                  mount:
                          - .sbt
                          - .ivy2
                  volumes:
                          - name: cache
                            path: /cache

volumes:
        - name: cache
          host:
                  path: /opt/drone/cache
