---
kind: pipeline
name: default

clone:
        disable: true

steps:

        - name: clone
          image: plugins/git:next
        - name: restore-cache
          image: drillster/drone-volume-cache
          settings:
                  restore: true
                  mount:
                          - /home/user/.sbt
                          - /home/user/.ivy2
                  volumes:
                          - name: cache
                            path: /cache

        - name: build
          image: tooom/docker-scala-node
          commands:
                  - id
                  - pwd
                  - ls -al
                  - echo @@@@@@@@@@@@@@@@@@@
                  - ls -al ..
                  - "touch a && echo source: RW || echo source: RO"
                  - "touch /a && echo root: RW || echo root: RO"
                  - "touch /drone/a && echo drone: RW || echo drone: RO"
                  - "touch /home/user/a && echo home: RW || echo home: RO"
                  - . ~/.nvm/nvm.sh
                  - sbt clean stage

        - name: save-cache
          image: drillster/drone-volume-cache
          settings:
                  rebuild: true
                  mount:
                          - /home/user/.sbt
                          - /home/user/.ivy2
                  volumes:
                          - name: cache
                            path: /cache

volumes:
        - name: cache
          host:
                  path: /opt/drone/cache
