kind: pipeline
name: default
workspace:
        base: /home/user
        path: /

steps:
        - name: restore-cache
          image: drillster/drone-volume-cache
          restore: true
          mount:
                - .sbt
                - .ivy2
          volumes:
                - /opt/drone/cache:/cache

        - name: build
          image: tooom/docker-scala-node
          commands: sbt clean stage

        - name: restore-cache
          image: drillster/drone-volume-cache
          rebuild: true
          mount:
                - .sbt
                - .ivy2
          volumes:
                - /opt/drone/cache:/cache
