language: scala
jdk:
- oraclejdk8
scala:
- 2.11.8
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
script:
- bin/setBintrayCredential
- bin/setDockerCredential
- bin/setGithubCredential
env:
  secure: BYEOJ0Jb2TsRelsHpaqMVHlJ+PpA9BSwDuBt9ksmo+UGt/CTrCSL8qVZWkMcqG//2lnAzlA+eqqvcLvWdtSR8tpNWxo9rss8OdgJ1VR/8pbcz0NRebNB7slbbMQnqn/vQDc/AJjmfsAfS0TC2eE/WU1CFmw8NzXVbgwc45v4Fkav9J+j9iqaM5R13Mt5gwdNjdna2Em6KbKmvOxPAl4IWDcLjIR3n2juapb8Ebp00F/6q2FyKaXP5jUNQb8xdhEaUQm/+MzbxrHfNUGeSzkECV442MtMj3Eh1FmN99D1V6+UjhMHXSj7Ae5E5ZaHGPa4AlOP67rnZgaq03bE90+9u7eRSa8wYF+W3B3KNOy1A1Wpe3v+SAb+jZI6Gmnc6+284BFMm2cRJtvw4babQGGIqniL8wI68r0tSaFwttHy3c/OOf0xGnqN7ErLxpkmiTlBaYa/0ST1wSq3D6/e7r0n294kO8Sjm7NwxdtBTpJsGYbjk+89OqEazvq9ET+sMpENL6BfVxD365dMjzeaAzXTeTba+KBLngRGa+sXNzw/ttS9baAkJ3db0+baSLnr8vKmrg0DyXbfWBd+anfV0s6w7+J/jDjVuwhBh1agm5Xas1qD6AElQT2ydtOoSBnrooUguprAeIcr4DbSCR9AyyKSwTDOVAi/jO8yMKgSfvEKFVw=
